# Generated by Django 5.2.3 on 2026-01-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_technician_ticket_assigned_technician_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
